#!/bin/bash

PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin

DB="$1"
USER="$2"
PASS="$3"

DATE=$(date +'%Y%m%d')

mariadb-dump -u $USER -p$3 $DB > /backups/$DB-$DATE.mysql

for file in $(find /backups -name "*.mysql" | sort | head -n -1)
do
        if [ "$file" != "" ] && [ -f $file ]; then
                rm -vf $file
        fi
done
